<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f82e317d-7bdf-40d3-b870-a8a35ddeb2c5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\images\cat.gif" />
  </ItemGroup>

</Project>
